import = [
    "~/.config/alacritty/themes/themes/campbell.toml"
]

live_config_reload = true

[window]
dynamic_padding = true
opacity = 0.7
blur = true
dynamic_title = true

[font]
size = 10.0

[cursor]
style = "Underline"

[mouse]
hide_when_typing = true

