user_pref("browser.pocket.enabled", false);
user_pref("browser.aboutConfig.showWarning", false);
user_pref("browser.geolocation.warning.infoURL", " ");
user_pref("geo.enabled", false);
user_pref("toolkit.crashreporter.infoURL", " ");
user_pref("browser.startup.page", 3);
user_pref("browser.newtabpage.activity-stream.showSponsored", false);
user_pref("browser.newtabpage.activity-stream.showSponsoredTopSites", false);
user_pref("browser.newtabpage.activity-stream.default.sites", false);
user_pref("geo.provider.use_geoclue", false);
user_pref("extensions.getAddons.showPane", false);
user_pref("extensions.htmlaboutaddons.recommendations.enabled", false);
user_pref("browser.discovery.enabled", false);
user_pref("browser.shopping.experience2023.enabled", false);
user_pref("datareporting.policy.dataSubmissionEnabled", false);
user_pref("datareporting.healthreport.uploadEnabled", false);
user_pref("toolkit.telemetry.unified", false);
user_pref("toolkit.telemetry.enabled", false);
user_pref("toolkit.telemetry.server", "data:,");
user_pref("toolkit.telemetry.archive.enabled", false);
user_pref("toolkit.telemetry.newProfilePing.enabled", false);
user_pref("toolkit.telemetry.shutdownPingSender.enabled", false);
user_pref("toolkit.telemetry.updatePing.enabled", false);
user_pref("toolkit.telemetry.bhrPing.enabled", false);
user_pref("toolkit.telemetry.firstShutdownPing.enabled", false);
user_pref("toolkit.telemetry.coverage.opt-out", true);
user_pref("toolkit.coverage.opt-out", true);
user_pref("toolkit.coverage.opt-out", true);
user_pref("toolkit.coverage.endpoint.base", "");
user_pref("browser.newtabpage.activity-stream.feeds.telemetry", false);
user_pref("browser.newtabpage.activity-stream.telemetry", false);
user_pref("app.shield.optoutstudies.enabled", false);
user_pref("app.normandy.enabled", false);
user_pref("app.normandy.api_url", "");
user_pref("breakpad.reportURL", "");
user_pref("browser.tabs.crashReporting.sendReport", false);
user_pref("browser.crashReports.unsubmittedCheck.autoSubmit2", false);
user_pref("app.normandy.api_url", " ");
user_pref("app.normandy.api_url", " ");
user_pref("extensions.pocket.bffApi", " ");
user_pref("extensions.pocket.api", " ");
user_pref("extensions.getAddons.discovery.api_url", " ");
user_pref("identity.fxaccounts.enabled", false);
user_pref("toolkit.telemetry.server_owner", "31");
user_pref("toolkit.telemetry.server", "31");
user_pref("toolkit.telemetry.dap_leader", "31");
user_pref("toolkit.telemetry.dap_leader_owner", "31");
user_pref("toolkit.telemetry.dap_helper_owner", "31");
user_pref("toolkit.telemetry.dap_helper", "31");
user_pref("browser.newtabpage.activity-stream.telemetry.structuredIngestion.endpoint", "31");
user_pref("identity.sync.tokenserver.uri", "31");
user_pref("extensions.webextensions.restrictedDomains", "31");
user_pref("privacy.restrict3rdpartystorage.partitionedHosts", "31");
user_pref("browser.safebrowsing.provider.google.advisoryName", "fuckgoogle");
user_pref("browser.safebrowsing.provider.google.advisoryURL", "31");
user_pref("browser.safebrowsing.provider.google.gethashURL", "31");
user_pref("browser.safebrowsing.provider.google.lists", "31");
user_pref("browser.safebrowsing.provider.google.reportMalwareMistakeURL", "31");
user_pref("browser.safebrowsing.provider.google.reportPhishMistakeURL", "31");
user_pref("browser.safebrowsing.provider.google.reportURL", "31");
user_pref("browser.safebrowsing.provider.google.updateURL", "31");
user_pref("browser.safebrowsing.provider.google4.advisoryName", "fuckgoogle");
user_pref("browser.safebrowsing.provider.google4.advisoryURL", "31");
user_pref("browser.safebrowsing.provider.google4.dataSharingURL", "31");
user_pref("browser.safebrowsing.provider.google4.gethashURL", "31");
user_pref("browser.safebrowsing.provider.google4.lists", "31");
user_pref("browser.safebrowsing.provider.google4.reportMalwareMistakeURL", "31");
user_pref("browser.safebrowsing.provider.google4.reportPhishMistakeURL", "31");
user_pref("browser.safebrowsing.provider.google4.reportURL", "31");
user_pref("browser.safebrowsing.provider.google4.updateURL", "31");
user_pref("browser.newtabpage.activity-stream.discoverystream.endpoints", "31");
user_pref("browser.newtabpage.activity-stream.feeds.section.topstories.options", "31");
user_pref("browser.newtabpage.activity-stream.fxaccounts.endpoint", "31");
user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.searchEngines", " 31");
user_pref("identity.sendtabpromo.url", "31");
user_pref("privacy.resistFingerprinting.block_mozAddonManager", true);
user_pref("extensions.quarantinedDomains.list", "31");
user_pref("browser.dataFeatureRecommendations.enabled", false);
user_pref("browser.newtabpage.activity-stream.feeds.recommendationprovider", false);
user_pref("geo.provider.network.url", "data:application/json,{"location": {"lat": 40.7590, "lng": -73.9845}, "accuracy": 27000.0}")
user_pref("browser.urlbar.groupLabels.enabled", false);
user_pref("browser.newtabpage.activity-stream.unifiedAds.endpoint", "31");
user_pref("browser.newtabpage.activity-stream.support.url", "31");
user_pref("extensions.recommendations.privacyPolicyUrl", "31");
user_pref("extensions.recommendations.themeRecommendationUrl", "31");
user_pref("remote.prefs.recommended", false);
user_pref("services.sync.prefs.sync.browser.", false);
user_pref("services.sync.prefs.sync.browser.newtabpage.activity-stream.showSponsoredTopSites", false);
user_pref("browser.urlbar.suggest.topsites", false);
user_pref("services.sync.prefs.sync.browser.urlbar.suggest.topsites", false);
user_pref("geo.prompt.testing", false);
user_pref("layout.spellcheckDefault", 0);
user_pref("services.sync.prefs.sync.layout.spellcheckDefault", false);
user_pref("browser.preferences.experimental", false);
user_pref("browser.preferences.moreFromMozilla", false);
user_pref("app.support.baseURL", "https://baturax.com/");
user_pref("browser.search.suggest.enabled", false);
user_pref("browser.translations.automaticallyPopup", false);
user_pref("browser.translations.enable", false);
user_pref("browser.translations.panelShown", false);
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
user_pref("svg.context-properties.content.enabled", true);
user_pref("layout.css.color-mix.enabled", true);
user_pref("",);
user_pref("",);
user_pref("",);
user_pref("",);
user_pref("",);
user_pref("",);

