#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor -d 󰫯 󰬀 󰫽 󰬄 󰫺
bspc config border_width 2
bspc config window_gap 8

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config pointer_follows_focus false
bspc config focus_by_distance false
bspc config focus_follows_pointer true

setxkbmap tr &
xsetroot -cursor_name left_ptr &

feh --bg-center --no-fehbg --randomize ~/.config/res/background/*
xset r rate 300 30 &
picom &
brillo -S 100
pkill pipewire &
xrandr --dpi 100 &
(sleep 3s && polybar) &
(sleep 2s && pipewire) &
