#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor -d 󰫯 󰬀 󰫽 󰬄 󰫺
bspc config border_width 2
bspc config window_gap 8

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config pointer_follows_focus false
bspc config focus_by_distance false
bspc config focus_follows_pointer true

bspc rule -a "discord" desktop=^5 follow=off
bspc rule -a "spotify" desktop=^5 follow=off
bspc rule -a "Telegram" desktop=^5 follow=off
bspc rule -a "firefox" desktop=^1 follow=off
bspc rule -a "Alacritty -e sudo xbps-install -Su" desktop=^2 follow=off

alacritty &
firefox &
ollama serve &

setxkbmap tr &
xsetroot -cursor_name left_ptr &
feh --bg-scale Pictures/zazu.jpeg
xset r rate 300 30 &
picom &
brillo -S 100 &
pkill pipewire &
xrandr --dpi 100 &
(sleep 3s && polybar) &
(sleep 2s && pipewire) &
