#! /bin/sh
pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5
bspc config border_width 2
bspc config window_gap 0

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config pointer_follows_focus false
bspc config focus_by_distance false
bspc config focus_follows_pointer true

setxkbmap tr &
xset r rate 300 30 
#/home/bai/.config/eww/a.sh &
brillo -S 100
#xrandr --dpi 100 
#fastcompmgr -o 0.4 -r 12 -c -C -i 0.9666
