bar:
  height: 26
  location: top
  background: 000000ff
  font: Hack-Bold:size=16

  right:

    - pulse:  # Burada 'pulse' bir anahtar olmalı
        content:
          sink_port: "alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__Headphones__sink"
          source_port: "alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__Headphones__sink.monitor"
        string:
          text: "{sink_percent}% ({sink_port})"


    - battery:
        name: BAT1
        poll-interval: 30000
        anchors:
          discharging: &discharging
            list:
              items:
                - ramp:
                    tag: capacity
                    items:
                      - string: {text: , font: Hack-Bold:size=16}
                      - string: {text: , font: Hack-Bold:size=16}
                      - string: {text: , font: Hack-Bold:size=16}
                      - string: {text: , foreground: 00ff00ff, font: Hack-Bold:size=16}
                - string: {text: "{capacity} "}
        content:
          map:
            conditions:
              state == unknown:
                <<: *discharging
              state == discharging:
                <<: *discharging
              state == charging:
                - string: {text: " ", foreground: 00ff00ff, font: Hack-Bold:size=16}
                - string: {text: "{capacity} "}
              state == full:
                - string: {text: , foreground: 00ff00ff, font: Hack-Bold:size=16}
                - string: {text: "{capacity}% full "}
              state == "not charging":
                - ramp:
                    tag: capacity
                    items:
                      - string: {text: , font: Hack-Bold:size=16}
                      - string: {text: , font: Hack-Bold:size=16}
                      - string: {text: , font: Hack-Bold:size=16}


                - string: {text: "{capacity} "}


    - clock:
        content:
          - string: {text: "{time}", font: "Hack-Bold:size=16"}
